name: instances-updater

on:
  schedule:
    - cron: '10 2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: get repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install html-table-parser-python3 pandas
      - name: run script
        run: python CrawlObject.py
      
      - name: commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update scrape
          commit_author: GitHub Actions <actions@github.com>